### ISSUE TITLE
no changes 

### ISSUE THREAD

**Issue by ammlr** [Magisk-Modules-Alt-Repo/NavBar_Resize_MIUI#1]
no changes to the navbar. my device miui 13

![Screenshot_2022-08-13-12-43-54-741_ginlemon flowerfree](https://user-images.githubusercontent.com/30746607/184470454-c289bb74-6525-4250-9fa6-ecddd07150cb.jpg)

**Comment by ammlr** [comment]
![Screenshot_2022-08-13-12-45-09-220_hottj hxrlwn](https://user-images.githubusercontent.com/30746607/184470503-282a188b-224a-4ef9-bcd9-1e6910d06ee6.jpg)

**Comment by CrazyBytesVE** [comment]
Not compatible with your phone.
